import platform
import cpuinfo
import os
import pandas as pd
import pdfkit as pdf
currentDirectory = os.getcwd();
from .Comparation import Method1,Method2,Method3,Method4

def generatePDF(dframe,tables,softwareTime,hardwareTime):
	pd.set_option('colheader_justify', 'center')   # FOR TABLE <th>
	html_string = '''
	<html>
		<head><title>Performance analysis</title></head>
		<link rel="stylesheet" type="text/css" href="{dirActual}/Performance/Resources/Stylesheet.css"/>
		<link rel="stylesheet" type="text/css" href="{dirActual}/Performance/Resources/df_style.css"/>
		<body> 
		<div>			
			<h1>PERFORMANCE ANALYSIS</h1>
			{ComputerInfo}
			{Software}
			{Hardware}
		</div>
		</body>
	</html>.
	'''
	html_string = html_string.format(	ComputerInfo= getComputerInfo(),
										Software= getSoftware(dframe,tables,softwareTime),
										Hardware= getHardware(hardwareTime),
										dirActual= currentDirectory)

	# OUTPUT AN HTML FILE
	htmlDir = currentDirectory + "/Output/Performance/myhtml.html"
	with open(htmlDir, 'w') as f:
		f.write(html_string)
	PdfFilename=currentDirectory +'/Output/Performance/Report.pdf'
	pdf.from_file(htmlDir, PdfFilename)


def getComputerInfo():
	computer_string = '''
			<h2>Computer characteristics</h2>
			<ul>
				<li><p>Computer: {computer}.</p></li>
				<li><p>Operative system: {operativeSystem} </p></li>
				<li><p>Version: {version}.</p></li>
				<li><p>Processor: {processor}</p></li>
				<li><p>CPU: {cpu}</p></li>
			</ul> '''
	computer_string = computer_string.format(	computer= platform.uname()[1],
												operativeSystem= platform.uname()[0],
												version= platform.uname()[2],
												processor= platform.processor(),
												cpu= cpuinfo.get_cpu_info()['brand'])
	return computer_string

def getComparation():
    Method1()
    Method2()
    Method3()
    [comE,rms] = Method4()
    print("Compararacion exacta: "+str(comE))
    print("RMS: "+str(rms))
    
    
    
def getHardware(hardwareTime):
	hardware_string = '''
			<h2>Hardware analysis</h2>
			<p>The process took {Time} seconds to execute</p>
			<p> The image generated by the FPGA is the following one: </p>
			<img src="{dirActual}/Output/Pictures/FPGA.png" alt=""/>	'''
	hardware_string = hardware_string.format(	dirActual= currentDirectory,
												Time= hardwareTime)
	return hardware_string

def getSoftware(dframe,tables,softwareTime): 
	
	software_string = '''
			<h2>Software analysis</h2>
			<p>The process took {Time} seconds to execute</p>
			<img src="{dirActual}/Output/Pictures/file.png" alt=""/>			
			<h3>Table 1</h3>
			<p> This table gives us the following information: </p>
			<ul>
				<li><p>time: the percentage of the total running time of the program used by this function. </p></li>
				<li><p>Accumulative seconds: a running sum of the number of seconds accounted for by this function and those listed above it.</p></li>
				<li><p>Self seconds: the number of seconds accounted for by this function alone. This is the major sort for this listing.</p></li>
				<li><p>Calls: the number of times this function was invoked, if this function is profiled, else blank.</p></li>
				<li><p>Self ms/call: the average number of milliseconds spent in this ms/call function per call, if this function is profiled, else blank.</p></li>
				<li><p>total ms/call: the average number of milliseconds spent in this function and its descendents per call, if this function is profiled, else blank.</p></li>
				<li><p>Name: the name of the function.</p></li>
			</ul>
			<p>Each sample counts as 0.01 seconds.</p>
			{table0}
			<p>To get a better understanding, some table columns were graphed</p>
			<img src="{dirActual}/Output/Performance/images/img1.png" alt="Image 1">
			<img src="{dirActual}/Output/Performance/images/img2.png" alt="Image 2">
			
			<h3>Table 2</h3>
			<p>This table describes the call tree of the program, and was sorted by the total amount of time spent in each function and its children.
			Each entry in this table consists of several lines.  The line with the
			index number at the left hand margin lists the current function.
			The lines above it list the functions that called this function,
			and the lines below it list the functions this one called. 
			This line lists:</p>
			<ul>
				<li><p>index: A unique number given to each element of the table. Index numbers are sorted numerically.
							The index number is printed next to every function name so it is easier to look up where the function is in the table. </p></li>
				<li><p>time:  This is the percentage of the 'total' time that was spent
							in this function and its children.  Note that due to
							different viewpoints, functions excluded by options, etc,
							these numbers will NOT add up to 100%.</p></li>
				<li><p>self:  This is the total amount of time spent in this function.</p></li>
				<li><p>children:  This is the total amount of time propagated into this function by its children.</p></li>
				<li><p>called:  This is the number of times the function was called. If the function called itself recursively, the number
								only includes non-recursive calls, and is followed by
								a '+' and the number of recursive calls.</p></li>
				<li><p>total ms/call: the average number of milliseconds spent in this function and its descendents per call, if this function is profiled, else blank.</p></li>
				<li><p>total ms/call: the average number of milliseconds spent in this function and its descendents per call, if this function is profiled, else blank.</p></li>
				<li><p>Name: the name of the function.</p></li>
			</ul> 
			<p>For the function's parents, the fields have the following meanings:</p>
			<ul>
				<li><p>self		This is the amount of time that was propagated directly from the function into this parent.</p></li>
				<li><p>children	This is the amount of time that was propagated from the function's children into this parent.</p></li>
				<li><p>called	This is the number of times this parent called the function '/' the total number of times the function
								was called.  Recursive calls to the function are not included in the number after the '/'.</p></li>
				<li><p>name		This is the name of the parent.  The parent's index
								number is printed after it.  If the parent is a
								member of a cycle, the cycle number is printed between
								the name and the index number.</p></li>
			</ul> 
		
			<h3>Table 2.1</h3> {table1} <br>
			<h3>Table 2.2</h3> {table2} <br> 
			<h3>Table 2.3</h3> {table3} <br> 
			<h3>Table 2.4</h3> {table4} <br> 
			<h3>Table 2.5</h3> {table5} <br>
			<h3>Table 2.6</h3> {table6} <br>'''
	software_string = software_string.format( 	Time=softwareTime,
                                                dirActual= currentDirectory,
                                                table0=dframe.to_html(classes='mystyle',index=False),
												table1=tables[0].to_html(classes='mystyle',index=False),
												table2=tables[1].to_html(classes='mystyle',index=False),
												table3=tables[2].to_html(classes='mystyle',index=False),
												table4=tables[3].to_html(classes='mystyle',index=False),
												table5=tables[4].to_html(classes='mystyle',index=False),
												table6=tables[5].to_html(classes='mystyle',index=False),
												table7=tables[6].to_html(classes='mystyle',index=False))
	return software_string
